main: dev.lksh.minecraft.plugins.timer.IndigestionTimer
name: IndigestionTimer
version: "1.0"
api-version: "1.20"
description: Timer for the lil_indigestion minecraft server
author: SnailyLuke
commands:
  createtimerevent:
    description: Create an event to run timers for
    usage: /createtimerevent <event-id>
    permission: indicards.createtimerevent
  settimereventname:
    description: Set/update the event name for an existing event
    usage: /settimereventname <event-id> <name> (name can be multiple words)
    permission: indicards.settimereventname
  gettimereventname:
    description: Gets the event name for an existing event
    usage: /gettimereventname <event-id>
    permission: indicards.gettimereventname
  settimereventstart:
    description: Sets the start position for a timer event
    usage: /settimereventstart <event-id> [<margin>]
    permission: indicards.settimereventstart
  settimereventend:
    description: Sets the start position for a timer event
    usage: /settimereventend <event-id> [<margin>]
    permission: indicards.settimereventend
permissions:
  indicards.createtimerevent:
    description: Allows createtimerevent command
    default: op
  indicards.settimereventname:
    description: Allows settimereventname command
    default: op
  indicards.gettimereventname:
    description: Allows gettimereventname command
    default: op
  indicards.settimereventstart:
    description: Allows settimereventstart command
    default: op
  indicards.settimereventend:
    description: Allows settimereventend command
    default: op
